# Generated by Django 3.1.3 on 2020-12-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letgo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imggal',
            name='imgdesc',
            field=models.TextField(),
        ),
    ]
