# Generated by Django 3.1.3 on 2020-12-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letgo', '0004_auto_20201213_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='homedesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.TextField()),
            ],
        ),
    ]
