# Generated by Django 3.1.3 on 2020-12-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letgo', '0005_homedesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage', models.ImageField(default='', upload_to='image/')),
                ('iconimage', models.ImageField(default='', upload_to='image/')),
                ('servicetitle', models.CharField(default='', max_length=100)),
                ('servicedesc', models.TextField(default='', max_length=250)),
                ('timeStamp', models.DateTimeField(blank=True, default='', null=True)),
                ('servicereadmore', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='imggal',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
