# Generated by Django 3.1.3 on 2020-12-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letgo', '0006_auto_20201220_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imggal',
            name='image',
            field=models.ImageField(upload_to='letgo/media/images/'),
        ),
    ]
