# Generated by Django 3.1.3 on 2020-12-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letgo', '0010_auto_20201221_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imggal',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
