# Generated by Django 3.1.3 on 2020-12-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letgo', '0011_auto_20201222_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutdesc', models.TextField()),
                ('aboutimage', models.ImageField(default='', upload_to='images/')),
                ('timeStamp', models.DateTimeField(blank=True, default='', null=True)),
            ],
        ),
    ]
